# Generated by Django 4.1.7 on 2023-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('confirmed_by', models.TextField()),
                ('is_confirmed', models.BooleanField()),
            ],
            options={
                'db_table': 'confirmation',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
            ],
            options={
                'db_table': 'nomination',
            },
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('rejected_by', models.TextField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'rejection',
            },
        ),
    ]
