# Generated by Django 4.1.7 on 2023-03-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated_by', models.IntegerField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingsession')),
            ],
            options={
                'db_table': 'nomination',
            },
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_by', models.TextField()),
                ('reason', models.TextField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.nomination')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingsession')),
            ],
            options={
                'db_table': 'rejection',
            },
        ),
    ]
