# Generated by Django 4.1.7 on 2023-03-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
