# Generated by Django 4.1.7 on 2023-04-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='nominated_by',
            new_name='nominated_from',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='emp',
            new_name='nominated_to',
        ),
    ]
