# Generated by Django 4.1.7 on 2023-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0002_rename_nominated_by_nomination_nominated_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominated_to',
            field=models.IntegerField(),
        ),
    ]
