# Generated by Django 4.1.7 on 2023-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0002_rename_to_emp_id_nomination_confirm_by_emp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='confirm_status',
            field=models.BooleanField(null=True),
        ),
    ]
