# Generated by Django 4.1.7 on 2023-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0003_alter_nomination_confirm_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='to_add_emp',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='nomination',
            old_name='confirm_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='confirm_by_emp',
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominated_by',
            field=models.IntegerField(null=True),
        ),
    ]
