# Generated by Django 4.1.7 on 2023-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.TextField()),
                ('emp_role', models.TextField()),
                ('rm_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
