# Generated by Django 4.1.7 on 2023-03-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emp_name', models.TextField()),
                ('emp_category', models.TextField()),
                ('rm_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
