# Generated by Django 4.1.7 on 2023-03-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_rm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rm_id',
            new_name='rm',
        ),
    ]
