# Generated by Django 4.1.7 on 2023-03-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_emp_id_alter_employee_rm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RM_Requested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_name', models.TextField()),
                ('urgency', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('tm_acceptance', models.TextField()),
                ('rej_reason', models.TextField()),
                ('session_date', models.TextField()),
                ('session_time', models.TextField()),
            ],
            options={
                'db_table': 'RM_Requested',
            },
        ),
    ]
