# Generated by Django 4.1.7 on 2023-03-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('training_status', models.TextField()),
            ],
            options={
                'db_table': 'Enrollment',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('feedback_q1', models.IntegerField()),
                ('feedback_q2', models.IntegerField()),
                ('feedback_q3', models.IntegerField()),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('training_name', models.TextField()),
                ('emp_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Training',
            },
        ),
        migrations.CreateModel(
            name='Training_Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
            ],
            options={
                'db_table': 'Training_Session',
            },
        ),
    ]
