# Generated by Django 4.1.7 on 2023-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('training_name', models.TextField()),
                ('emp_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Training',
            },
        ),
        migrations.CreateModel(
            name='Training_Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
            ],
            options={
                'db_table': 'Training_Session',
            },
        ),
    ]
