# Generated by Django 4.1.7 on 2023-03-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='trainer_name',
            new_name='training_name',
        ),
    ]
