# Generated by Django 4.1.7 on 2023-03-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='acceptance_status',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
