# Generated by Django 4.1.7 on 2023-03-21 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
